import Feed from "../component/Feed";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Login from "../component/Login";
import Sidebar from "../component/Sidebar";
import { AppContext } from "@/contexts/AppContext";
import { useContext } from "react";
import Modal from "@/component/Modal";
import Widgets from "@/component/Widgets";
// import Trending from '@/component/Trending'
  
  export default function Home({ newsResults, randomUsersResults}) {
  const { data: session } = useSession();
  const [appContext] = useContext(AppContext);

  if (!session) return <Login />;

  return (
    <div>
      <Head>
        <title>Twitter-Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon/favicon.ico" />
      </Head>

      <main className="flex min-h-screen mx-auto">
        <Sidebar />
        <div className="flex gap-6">
          <Feed />
          {/* <Trending /> */}
          {appContext?.isModalOpen && <Modal />}
          <Widgets newsResults={newsResults?.articles} randomUsersResults ={randomUsersResults.results}/>
        </div>
      </main>
    </div>
  );
}
// News
export async function getServerSideProps() {
  const newsResults = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/business/in.json"
  ).then((res) => res.json());
// Follow
let randomUsersResults = [];

try {
  const res = await fetch(
    "https://randomuser.me/api/?results=30&inc=name,login,picture"
  );

  randomUsersResults = await res.json();
} catch (e) {
  randomUsersResults = [];
}





  return {
    props: {
      newsResults,
  randomUsersResults,

    },
  };
}
